# Generated by Django 5.2.9 on 2026-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tokens', '0005_allow_multiple_custom_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetoken',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last token validation check', null=True),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='last_validation_message',
            field=models.CharField(blank=True, help_text='Human-readable message from the last validation check', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicetoken',
            name='last_validation_valid',
            field=models.BooleanField(blank=True, help_text='Result of the last validation check (True=valid, False=invalid, None=never checked)', null=True),
        ),
    ]
